---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE}
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      roles_path: "$HOME/.ansible/roles/:/tmp"
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
