---
- name: Verify
  hosts: all
  connection: docker
  become: true
  vars:
    ansible_user: ansible

  tasks:
    - name: Check whether Docker installed
      ansible.builtin.command: docker --version
      ignore_errors: true
      register: docker_installed
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure Docker is installed
      ansible.builtin.debug:
        var: docker_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
